Add minecraft & loader versions to processResources for fabric.mod.json
DemonWav/MinecraftDevIntelliJ pull request #1963
Opened 2023-03-10 16:34 UTC by Mysterious-Dev

Close #1962.

I don't include modid intentionally to let modder decide if he want to name his jar differently.

2023-03-10 16:50 UTC, Mysterious-Dev commented
All tests passed ^^.

2023-03-19 13:33 UTC, RedNesto requested changes

2023-03-19 13:33 UTC, RedNesto commented on src/main/resources/fileTemplates/j2ee/fabric/fabric_build.gradle.ft
> +        expand "version": project.version, 'minecraft_version': project.minecraft_version, 'loader_version': project.loader_version
```suggestion
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
```

2023-03-19 17:14 UTC, Mysterious-Dev commented on src/main/resources/fileTemplates/j2ee/fabric/fabric_build.gradle.ft
> +        expand "version": project.version, 'minecraft_version': project.minecraft_version, 'loader_version': project.loader_version
Done

2023-03-24 18:44 UTC, RedNesto approved these changes

2023-03-24 18:44 UTC, merged