MixinExtras: Add handler signature support for expressions.
DemonWav/MinecraftDevIntelliJ pull request #2244
Opened 2024-02-25 18:03 UTC by LlamaLad7

There are still 2 things to address, but you'd probably be better placed to implement them than me.
1. It doesn't handle `int-like` types. Ideally the user would be presented with a dropdown of the suitable types so they can choose. All int-like types within the handler should match (at least with the current possible targets). If that is too much to ask then it should probably just treat them as `int` types, but I do worry the users would get confused when they expected e.g. a char and have to change it themselves.
2. Not a direct result of this PR but the name suggestion code suggests duplicate names for parameters of the same type, which causes issues. This is noticeable e.g. when wrapping a comparison.

2024-02-25 18:04 UTC, LlamaLad7 commented
...

2024-02-25 19:43 UTC, RedNesto commented
Erm I guess this should only trigger when targeting a release branch

2024-03-07 20:02 UTC, Earthcomputer requested changes

2024-03-07 20:02 UTC, Earthcomputer commented on src/main/kotlin/platform/mixin/handlers/mixinextras/TargetInsn.kt
> +package com.demonwav.mcdev.platform.mixin.handlers.mixinextras
Please add the missing license header

2024-03-07 20:18 UTC, merged