Add support for MixinExtras expressions
DemonWav/MinecraftDevIntelliJ pull request #2274
Opened 2024-03-31 08:59 UTC by Earthcomputer

See [Llama's gist](https://gist.github.com/LlamaLad7/ac2f4ced03d21afddde80c5c5e9b302f) for a (slightly outdated) overview of what MixinExtras expressions are. Without IDE support, ME expressions would be really inconvenient to write, more so than other mixin features.

ME expression syntax is support through a custom language in IntelliJ, through the use of language injection. To make this nicer to work with, I have slightly extended the ME expression language. Definitions are prefixed with the `class` keyword, and then a boolean literal for whether they are a type or not. Expressions are surrounded with `do { ... }`. For example:
```java
@Definition(id = "Integer", type = Integer.class)
@Definition(id = "x", local = @Local(type = Object.class, ordinal = 0))
@Expression("(Integer) x")
```
would produce the following injected ME expression file:
```java
class true Integer
class false x
do { (Integer) x }
```

This feature is basically done now, the only thing left is to switch away from the JitPack version of MixinExtras and use the library they'll provide for us, which will hopefully have the same interface.

Don't worry about the amount of commits, I'll squash them all on merge.

2024-04-14 04:34 UTC, DenWav requested changes
Well this PR is insane. I don't really know anything about MixinExtras, and can barely follow parts of this PR, and can't follow other parts at all. The code seems fine, it's just going over my head in the more complicated places, but I don't have a problem with trusting you. I did look at (most) of the code in this PR at least, even if I don't really know all of what's going on.

I apologize that the only comments I have are unimportant nitpicks, again I'm going mostly on trust here. Get the tests passing and address these and I'm happy to call this one good to go.

2024-04-14 04:34 UTC, DenWav commented on build.gradle.kts
> +    implementation("org.ow2.asm:asm-util:9.3")
Add the Maven coordinates to the `gradle/libs.versions.toml` file.

2024-04-14 04:34 UTC, DenWav commented on src/main/grammars/MEExpressionLexer.flex
> +%eof}
What's this here for?

Referring to this:
```
%eof{ return;
%eof}
```

2024-04-14 04:34 UTC, DenWav commented on src/main/grammars/MEExpressionLexer.flex
> +%type IElementType
Nit picking (I'm sorry, I know) but I like to just keep this bit consistent with the other flex files we have - like [this](https://github.com/minecraft-dev/MinecraftDev/blob/dev/src/main/grammars/AtLexer.flex#L36-L40), with `%unicode` after the states.

The only reason I point this out is just because I find it easier to keep track when they're the same.

2024-04-14 04:34 UTC, DenWav commented on src/main/grammars/MEExpressionLexer.flex
> +    {WHITE_SPACE}+ { yybegin(YYINITIAL); return TokenType.WHITE_SPACE; }
It's not necessary to call `yybegin(YYINITIAL)` when you're already in the `YYINITIAL` state. You only need that if you're changing state.

2024-04-14 04:34 UTC, DenWav commented on src/main/kotlin/platform/mixin/expression/MEExpressionInjector.kt
> +        var isFrankenstein = false
Can you explain what frankenstein means with a comment here?

2024-04-14 11:19 UTC, RedNesto reviewed
This looks really good.

I don't have much to say about the features added as I'm not familiar with MixinExtras.

Also not sure about those `invokeLater { WriteCommandAction[...] }` patterns. It might be the only way to achieve this today, but it might age poorly because of https://youtrack.jetbrains.com/issue/IJPL-53

2024-04-14 11:19 UTC, RedNesto commented on src/main/resources/META-INF/plugin.xml
> +        <lang.foldingBuilder language="JAVA" implementationClass="com.demonwav.mcdev.platform.mixin.expression.MEDefinitionFoldingBuilder"/>
Nitpick: why is this not with the other ME EPs a bit further down?

2024-04-14 11:19 UTC, RedNesto commented on src/main/kotlin/platform/mixin/util/LocalVariables.kt
> +        val variable: PsiVariable? = null,
I'm not super familiar with that part of the Mixin support, but having fields containing direct references to PsiElements might end up causing leaks, using pointers would be more appropriate.

2024-04-14 11:19 UTC, RedNesto commented on src/main/kotlin/util/psi-utils.kt
> +    }
This is not super consequential, but using Kotlin's `withLock` extension function avoids that Java try/finally-unlock boilerplate.

2024-04-14 11:46 UTC, Earthcomputer commented on src/main/grammars/MEExpressionLexer.flex
> +%eof}
No idea. I copied it from the IntelliJ language tutorial

2024-04-14 11:46 UTC, Earthcomputer commented on build.gradle.kts
> +    implementation("org.ow2.asm:asm-util:9.3")
These are all temporary while we wait for the MixinExtras standalone library, when they'll be transitive dependencies.

2024-04-14 11:47 UTC, Earthcomputer commented on src/main/grammars/MEExpressionLexer.flex
> +    {WHITE_SPACE}+ { yybegin(YYINITIAL); return TokenType.WHITE_SPACE; }
Really? I didn't realize

2024-04-14 11:57 UTC, Earthcomputer commented on src/main/kotlin/platform/mixin/util/LocalVariables.kt
> +        val variable: PsiVariable? = null,
I don't think this object is supposed to be stored anywhere. I'll add that to the docs though.

2024-04-14 11:59 UTC, Earthcomputer commented
I think once write actions are allowed outside of the EDT we'll have to make a general sweep of the codebase to look for cases like these where we use `invokeLater` for write actions.

2024-04-19 18:36 UTC, Earthcomputer commented on src/main/kotlin/util/psi-utils.kt
> +    }
It didn't let me do this for some reason, prompting me to add kotlin stdlib to the classpath, but don't we already have stdlib-jdk8?

2024-04-21 12:23 UTC, LlamaLad7 commented on src/main/kotlin/util/psi-utils.kt
> +    }
Perhaps more to the point kt also has `ReentrantReadWriteLock().read { }` and a similar write method.

2024-07-12 18:36 UTC, LlamaLad7 approved these changes

2024-07-12 19:43 UTC, Earthcomputer commented on src/main/kotlin/util/psi-utils.kt
> +    }
Couldn't find `ReentrantReadWriteLock.read`

2024-07-12 19:44 UTC, Earthcomputer commented on src/main/resources/META-INF/plugin.xml
> +        <lang.foldingBuilder language="JAVA" implementationClass="com.demonwav.mcdev.platform.mixin.expression.MEDefinitionFoldingBuilder"/>
Because I put it in the folding category

2024-07-12 19:45 UTC, LlamaLad7 commented on src/main/kotlin/util/psi-utils.kt
> +    }
It's only on `ReentrantReadWriteLock`, not `ReadWriteLock`, so the key's type needs to be more specific.

2024-07-12 19:46 UTC, Earthcomputer commented on src/main/kotlin/util/psi-utils.kt
> +    }
Ah yes sorry. But it's also in kotlin stdlib, and it's giving me the same problem as `withLock`.

2024-07-12 19:49 UTC, LlamaLad7 commented on src/main/kotlin/util/psi-utils.kt
> +    }
Might be an IDEA cache issue? I can build fine having switched to `read` and `write`

2024-07-12 19:55 UTC, Earthcomputer commented on src/main/kotlin/util/psi-utils.kt
> +    }
Yeah must have been. I can use it now.

2024-07-12 20:16 UTC, merged