Add json5 support to mixin config jsons
DemonWav/MinecraftDevIntelliJ pull request #2375
Opened 2024-09-18 05:26 UTC by Bawnorton

Allow mixin config json inspections and references to recognise mixin configs of the json5 file type

## Motivation

[Stonecutter](https://github.com/kikugie/stonecutter), a gradle pre-processor plugin has been gaining traction for it's use in multi-loader, multi-version projects, and a plugin that was developed alongside it, [j52j](https://github.com/kikugie/j52j), which converts json5 files to json during compilation allowing versioned comments within json files:

<https://github.com/Bawnorton/BetterTrims/blob/8558c398e0cd5a85fdd5dce6b2ed9e410d239743/src/main/resources/bettertrims.mixins.json5#L6-L12>

mcdev doesn't recognise json5 as a valid file type for mixin config jsons, so this pr adds that support.

2024-09-19 11:39 UTC, RedNesto requested changes
I don't think all of those changes are needed at all. Simply changing `filenameRegex` by adding `5?` at the end of the extension should do the job.

2024-09-19 14:04 UTC, Bawnorton commented
I tested that initially and it causes a json language inspection in the mixin json for violating the json standard as the config file type specifies that the language is Json not Json5

2024-09-23 09:50 UTC, RedNesto requested changes

2024-09-23 09:50 UTC, RedNesto commented on src/main/kotlin/platform/mixin/config/reference/MixinConfigReferenceContributor.kt
> +        val jsonPattern = PlatformPatterns.psiElement(JsonStringLiteral::class.java)
This isn't a great solution, a simpler way to do that is using an `or` pattern:

```kotlin
        val anyMixinConfigFileType = StandardPatterns.or(
            StandardPatterns.`object`(MixinConfigFileType.Json),
            StandardPatterns.`object`(MixinConfigFileType.Json5)
        )
        val pattern = PlatformPatterns.psiElement(JsonStringLiteral::class.java)
            .inFile(PlatformPatterns.psiFile().withFileType(anyMixinConfigFileType))
```

2024-09-23 16:17 UTC, RedNesto approved these changes
Looks good now, thanks for the PR 👍

2024-09-23 16:17 UTC, merged