Fix Forge project generation for MC1.12+ and enhance Minecraft version selection
DemonWav/MinecraftDevIntelliJ pull request #272
Opened 2017-07-20 12:01 UTC by PaleoCrafter

As of version 1.12 of Minecraft, Forge projects are required to use ForgeGradle 2.3, while earlier version should still use FG 2.2. This was not accounted for in the plugin, but this PR fixes the issue by making the ForgeGradle version variable based on the Minecraft version. Since I implemented a `SemanticVersion` utility for this which allows us to compare Minecraft (and Forge, technically) version easily, I also "fixed" the way the initial Minecraft version is retrieved in the wizard, namely by properly comparing the versions, assuming semantic versioning. The previous method of just comparing version strings was (currently) always yielding "1.9.4", since the String comparison first favours length and then compares each character if two lengths are equal. This did not respect the components of the semantic versions.

2017-08-05 20:15 UTC, kashike approved these changes

2017-08-06 20:30 UTC, DenWav requested changes

2017-08-06 20:30 UTC, DemonWav commented on src/main/kotlin/com/demonwav/mcdev/util/SemanticVersion.kt
> +    val parts = value.split(".").map {
This should be `.split('.')` (split on the char rather than the String).

2017-08-06 20:30 UTC, DemonWav commented on src/main/kotlin/com/demonwav/mcdev/util/SemanticVersion.kt
> +            PreReleasePart(subParts[0].toInt(), subParts[1].toInt())
How confident are we in the format of these versions that this will never have index out of bounds issues?

2017-08-06 20:30 UTC, DemonWav commented on src/main/kotlin/com/demonwav/mcdev/util/SemanticVersion.kt
> +        val result = parts.zip(other.parts).fold(0, { acc, (a, b) -> if (acc == -1) acc else a.compareTo(b) })
This should use function syntax:

`.fold(0) { ... }`

2017-08-07 17:11 UTC, PaleoCrafter commented on src/main/kotlin/com/demonwav/mcdev/util/SemanticVersion.kt
> +            PreReleasePart(subParts[0].toInt(), subParts[1].toInt())
In the context of MC versions, we can be 100% confident, I think, but I'll add some safeguards to prevent more general purpose usage blowing up.

2017-08-11 04:07 UTC, DenWav approved these changes

2017-08-11 04:07 UTC, merged