Introduce Waterfall support
DemonWav/MinecraftDevIntelliJ pull request #314
Opened 2017-10-14 16:26 UTC by jamierocks

2017-10-15 15:12 UTC, stephan-gh submitted a review, later dismissed
You need to add stuff here: 
https://github.com/minecraft-dev/MinecraftDev/blob/f483d38c82e1b233d3bff21b22cf0360c22f5319/src/main/kotlin/com/demonwav/mcdev/creator/MinecraftProjectCreator.kt#L189-L195

2017-10-16 00:09 UTC, DenWav requested changes
The information panel needs to be expanded appropriately to be able to hold all the lines if someone is crazy enough to select every platform selectable. Notice the Neptune information is pushed below the visible line.

![screen shot 2017-10-15 at 7 07 38 pm](https://user-images.githubusercontent.com/1332104/31590797-574f0ce4-b1dc-11e7-8733-b142dedc3a37.png)

2017-10-16 00:18 UTC, DemonWav commented
Actually, since that issue was added with the Canary PR, and I missed that detail there, I went ahead and fixed it in [`57a8bb0`](https://github.com/minecraft-dev/MinecraftDev/commit/57a8bb0a7687ab5a84aa1b74bb7ab1f910fdb248). Make sure to rebase off `dev` so the merge can fast-foward.

2017-10-16 00:18 UTC, DenWav approved these changes

2017-10-18 01:06 UTC, merged