Small addition and fix in Mixin Module
DemonWav/MinecraftDevIntelliJ pull request #817
Opened 2021-01-18 17:32 UTC by LlamaLad7

Adds parameter and return type checking for @ModifyArgs
Resolves outer class constructor param being required; it is now treated as part of the method's optional parameters

2021-01-21 17:48 UTC, LlamaLad7 commented
This validates the type argument of `@ModifyArgs` mixins, not `@ModifyArg` mixins. I was initially planning to do `@ModifyArg` as well, but they get special treatment in that you can either take a single arg, or all the method's args, and I couldn't find a way to represent that with the `ParameterGroup`s currently in place.

2021-02-17 17:52 UTC, RedNesto requested changes
Could you add tests for ModifyArgs ?
The rest LGTM.

2021-02-17 21:47 UTC, LlamaLad7 commented
In the process of writing a test I discovered that the fix was inserting the fully-qualified `Args` type instead of using the import.
This is only reproduceable inside the test environment, and when using `runIde` it all works fine.
It appears that not using the `thin` version of the Mixin dependency fixes this (perhaps the thin version doesn't include that type?)
Would you rather I allow the test to insert the fully-qualified Type, or depend on the non-thin version of Mixin?
Thanks.

2021-02-17 22:38 UTC, RedNesto commented
I'd say use the non-thin version for now, but I'd like input from @DemonWav about this.

2021-02-18 11:01 UTC, RedNesto requested changes

2021-02-18 11:01 UTC, RedNesto commented on src/test/kotlin/platform/mixin/InvalidInjectorMethodSignatureFixTest.kt
> +                            int i = Integer.parseInt("FF", 16);
The variable should be called something else, `i` is already used as a parameter. I don't know if it can conflict with anything, just in case.

2021-02-18 11:05 UTC, LlamaLad7 commented on src/test/kotlin/platform/mixin/InvalidInjectorMethodSignatureFixTest.kt
> +                            int i = Integer.parseInt("FF", 16);
Whoops I didn't see that.

2021-02-19 06:55 UTC, DemonWav commented
That's interesting, iirc thin means it only includes the API classes, so it should be included. It's been a while though - @Mumfrey would know either way.

2021-02-28 07:40 UTC, DemonWav approved these changes
I think this looks good to go.

2021-02-28 09:07 UTC, RedNesto approved these changes

2021-02-28 14:17 UTC, Earthcomputer approved these changes

2021-02-28 19:32 UTC, merged