Added mixin support for forge (#155)
DemonWav/MinecraftDevIntelliJ pull request #856
Opened 2021-04-27 08:49 UTC by MrAn0nym

(Currently only compatible with fg3)
Additional changes:
 - Modified ForgeProjectCreator.kt to work like FabricProjectCreator.kt)

2021-04-27 08:53 UTC, MrAn0nym commented
![image](https://user-images.githubusercontent.com/63542658/116214166-bc156480-a746-11eb-874e-8cdf7ed7eaaf.png)

2021-04-27 10:09 UTC, RedNesto requested changes
Works correctly. The major issue right now is that the build.gradle unconditionally includes mixins (with the checkbox unchecked in the creator.)

2021-04-27 10:09 UTC, RedNesto commented on src/main/kotlin/platform/forge/creator/Fg3Template.kt
> +    fun applyMixinConfigTemplate(
Add a blank line before this one

2021-04-27 10:09 UTC, RedNesto commented on src/main/kotlin/platform/forge/creator/Fg3Template.kt
> +        val artifactId = "${buildSystem.artifactId.toPackageName()}"
Move this variable up one line and use it in the string interpolation.
Might as well introduce another variable for the groupId to make the whole interpolation more readable.

2021-04-27 10:09 UTC, RedNesto commented on src/main/kotlin/platform/forge/creator/ForgeProjectCreator.kt
> +        val steps = mutableListOf(
Please revert changes to this method.

2021-04-27 10:09 UTC, RedNesto commented on src/main/kotlin/platform/forge/creator/ForgeProjectCreator.kt
> +        val steps = mutableListOf(
Ditto

2021-04-27 10:09 UTC, RedNesto commented on src/main/kotlin/util/MinecraftTemplates.kt
> +        const val FORGE_MIXINS_JSON_TEMPLATE = "forge_mixins.json"
Perhaps rename the file to `Forge Mixins Config.json` for consistency?

2021-04-27 10:09 UTC, RedNesto commented on src/main/resources/fileTemplates/j2ee/forge/Forge (1.13+) build.gradle.ft
> +        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
Please guard all those additions behind a template condition (similarly to `HAS_DATA` used below in this file), let's not pollute everyone's build.gradle with stuff they won't use.

Also, the refmap configuration is missing.

2021-04-27 10:09 UTC, RedNesto commented on src/main/resources/fileTemplates/j2ee/forge/Forge (1.13+) build.gradle.ft
> +            arg "-mixin.config=${ARTIFACT_ID}.mixins.json"
Could you add it to the server configuration too ?

2021-04-27 10:49 UTC, MrAn0nym commented on src/main/kotlin/platform/forge/creator/Fg3Template.kt
> +        val artifactId = "${buildSystem.artifactId.toPackageName()}"
>Might as well introduce another variable for the groupId to make the whole interpolation more readable.
Do you mean replacing `${PACKAGE_NAME}` with `${groupId}.${artifactId}`?

2021-04-27 11:27 UTC, RedNesto commented on src/main/kotlin/platform/forge/creator/Fg3Template.kt
> +        val artifactId = "${buildSystem.artifactId.toPackageName()}"
I mean
```kotlin
        val groupId = buildSystem.groupId.toPackageName()
        val artifactId = buildSystem.artifactId.toPackageName()
        val packageName = "$groupId.$artifactId.mixin"
```

2021-04-27 18:28 UTC, RedNesto commented
Oh, one last thing I forgot: could you make the Use Mixins option enabled/selectable only if the selected Minecraft version is >= 1.16.1 ? (Should be the correct version IIRC)

2021-04-27 20:07 UTC, SizableShrimp commented
Mixins are supported on 1.15.2+ and 1.16.1+ dependent on the forge version a player uses, I forget the specific versions. So this is slightly inaccurate.

2021-04-27 20:24 UTC, RedNesto commented
You're right, [0.8.2 was added in 1.15.2-31.2.45](https://maven.minecraftforge.net/net/minecraftforge/forge/1.15.2-31.2.45/forge-1.15.2-31.2.45-changelog.txt)

I don't know how much effort would be required to get the mixin version used by a specific forge build. We could use it for the `annotationProcessor` dependency (and determining if the build includes Mixin in the first place).

2021-04-27 20:25 UTC, SizableShrimp commented
> 
> 
> You're right, [0.8.2 was added in 1.15.2-31.2.45](https://maven.minecraftforge.net/net/minecraftforge/forge/1.15.2-31.2.45/forge-1.15.2-31.2.45-changelog.txt)
> 
> I don't know how much effort would be required to get the mixin version used by a specific forge build. We could use it for the `annotationProcessor` dependency (and determining if the build includes Mixin in the first place).

`MixinBootstrap.VERSION`

2021-04-27 20:29 UTC, RedNesto commented
I doubt we can get it at project creation time ^^. This information might be present in some POM the plugin can download and parse, I can't dig into it for now unfortunately.

2021-04-29 08:46 UTC, RedNesto commented on src/main/kotlin/platform/forge/creator/ForgeProjectSettingsWizard.kt
> +
The first line is too long, and might fail if `forgeVersionBox.selectedItem` for some reason.
`SemanticVersion.release` can also be used for hardcoded versions:
```suggestion
        val selectedVersion = forgeVersionBox.selectedItem as? SemanticVersion ?: return@ActionListener
        val supportedMixinVersion = selectedVersion >= SemanticVersion.release(31, 2, 45)
        mixinsCheckbox.isEnabled = supportedMixinVersion
        mixinsCheckbox.isSelected = supportedMixinVersion
```

Other than that it looks good enough, the "simple" comparison used here does the job for me, I don't expect people to use forge versions that are more than 6 months old.

2021-04-29 15:30 UTC, RedNesto approved these changes

2021-05-06 08:44 UTC, RedNesto requested changes
One last thing (hopefully): could you disable Mixins by default?
We prefer to keep coremodding opt-in for forge.

2021-05-06 09:26 UTC, MrAn0nym commented
Done ^^

2021-05-06 10:21 UTC, RedNesto approved these changes

2021-05-06 11:01 UTC, merged